# Generated by Django 5.0.3 on 2024-03-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_accessoriestype_slug_alter_brand_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
